server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.252:8848,192.168.31.252:8858,192.168.31.252:8868
    gateway:
      routes:
        - id: authorization
          uri: lb://authorization
          predicates:
            - Path=/auth/**